### ISSUE TITLE
Alloy-Optional Image thumbnails of topper image in categories page

### ISSUE THREAD

**Issue by sjenkin3** [elixirgraphics/foundry_issue_tracker#133]
If possible, have an image of a thumbnail of the topper image of a posts that is viewed when a category link takes you to the categories page. 

![Tag architecture](https://user-images.githubusercontent.com/1313462/79773412-70dca080-82ff-11ea-9415-c2bca5549639.png)

**Comment by elixirgraphics** [comment]
Done!
