### ISSUE TITLE
Alloy- Read more Link Styling

### ISSUE THREAD

**Issue by sjenkin3** [elixirgraphics/foundry_issue_tracker#134]
If possible, an 
option to have just a Read More link that is not a button. Not a must have, a nice to have so that summaries view has a cleaner look.  Styled like the  Go Back button/link

<img width="332" alt="Go Back Link" src="https://user-images.githubusercontent.com/1313462/79773730-d2047400-82ff-11ea-8271-4810b5f8ea06.png">

**Comment by elixirgraphics** [comment]
Does this option fulfill what you're looking for on this feature request or did you have more in mind? Or just something different?

![CleanShot 2020-06-17 at 13 33 42](https://user-images.githubusercontent.com/2013801/84930448-4ad54180-b09f-11ea-8e7d-514fe4ba4d1a.png)
