### ISSUE TITLE
Alloy-Add Bold Text to Author Controls

### ISSUE THREAD

**Issue by sjenkin3** [elixirgraphics/foundry_issue_tracker#135]
Add a text bold setting to the author for summaries and full posts view. Basically the same settings that are available to the date and categories.Maybe add the author control to this area as well. Just have the checkbox here to enable the author.

<img width="333" alt="Date   Category Line" src="https://user-images.githubusercontent.com/1313462/79773826-ef394280-82ff-11ea-91bf-f248ba684398.png">

**Comment by elixirgraphics** [comment]
You can now bold, italicize and underline the author name as well.
