### ISSUE TITLE
Alloy-Shadows on New Layouts

### ISSUE THREAD

**Issue by sjenkin3** [elixirgraphics/foundry_issue_tracker#136]
I believe this is on your todo list. But, separate the posts summaries in the summaries view.
Also, the posts topper images should go edge to edge when there is a shadow applied to the content.

<img width="2122" alt="test sourceorderlab com" src="https://user-images.githubusercontent.com/1313462/79773957-20197780-8300-11ea-8686-cac145485af8.png">

**Comment by elixirgraphics** [comment]
Done.
