### ISSUE TITLE
Alloy Beta Margin "Summaries-Space Between" issue

### ISSUE THREAD

**Issue by sjenkin3** [elixirgraphics/foundry_issue_tracker#150]
While using layout 5, on mobile view in portrait mode, there is an inconsistancy in spacing of blog entries. First and second entry is fne, the next two entries the margin is decreased. 
![CleanShot 2020-05-24 at 12 25 14@2x](https://user-images.githubusercontent.com/1313462/82759182-a6225580-9db9-11ea-9aac-d382331a03a2.png)

**Comment by elixirgraphics** [comment]
Looks like it could be that we need to apply the spacing applied to the `row` to the individual posts instead.

**Comment by elixirgraphics** [comment]
Good catch on this one @sjenkin3.

I think this should be fixed in the next update. Once I send out that update let me know if it is fixed for you.
