### ISSUE TITLE
Add Blur Option to Backdrop Stack

### ISSUE THREAD

**Issue by sjenkin3** [elixirgraphics/foundry_issue_tracker#23]
@elixirgraphics  nice feature, if possible, to add a blur overlay to an image for instance in the Background Stack.

**Comment by elixirgraphics** [comment]
Might work. Will take a peek.

**Comment by elixirgraphics** [comment]
The blur javascript / CSS for this unfortunately affects the contents of the backdrop stack as well as the background.
