### ISSUE TITLE
Mega menu full width option

### ISSUE THREAD

**Issue by sjenkin3** [elixirgraphics/foundry_issue_tracker#24]
If possible, add the option to have the dropdown area be full width of the screen.

**Comment by elixirgraphics** [comment]
I'll look at this. It might be possible, but I'm not 100% sure without diving into it.

**Comment by elixirgraphics** [comment]
This looks to be pretty difficult with the way the navigation is structured. I think it could be done, but it could break other things in the process. Will keep on it for a little longer, but just wanted to provide an update.

**Comment by elixirgraphics** [comment]
Should be in v0.4.1 beta update to testing
