### ISSUE TITLE
Typeface stack control for Card Stack

### ISSUE THREAD

**Issue by sjenkin3** [elixirgraphics/foundry_issue_tracker#33]
Will the card stack get the typeface stack control for the paragraph and header elements?

**Comment by elixirgraphics** [comment]
These should have Typeface integration as well. I'll add them to my list.

**Comment by elixirgraphics** [comment]
Added in as of:
https://github.com/elixirgraphics/Foundry/commit/2e41fe85c149697d18f66f1739f27e5cb0f4e889
https://github.com/elixirgraphics/Foundry/commit/da42ecc10b33b86eee446f890fcf5ac2fab37fcd
