### ISSUE TITLE
Lock Background option for Background stack for background image

### ISSUE THREAD

**Issue by sjenkin3** [elixirgraphics/foundry_issue_tracker#37]
Add a checkbox to enable lock background when an image is selected for the background stack.

**Comment by elixirgraphics** [comment]
I'll give this a look. Locked backgrounds can be a pain.

**Comment by elixirgraphics** [comment]
Just getting back to this issue. This was a request for the Backdrop stack, right?

**Comment by sjenkin3** [comment]
yes

**Comment by elixirgraphics** [comment]
Added
