### ISSUE TITLE
Feature request for Hover Stack in Potion pack

### ISSUE THREAD

**Issue by sjenkin3** [elixirgraphics/foundry_issue_tracker#49]
Have the ability to center the content in the container vertically.

**Comment by elixirgraphics** [comment]
Each of the hover effects are different and their positioning determined by the individual effect. These are pre-baked into the library used for the stack. I can look at it, but I don't know if it will be possible without re-writing a good deal of the effects, or providing alternate effects.

**Comment by elixirgraphics** [comment]
Took a look at this. I _think_ can do this. Will take a bit of restructuring. It will only center vertically within the overlay portion. So if the overlay portion covers just 2/3 of the image it will be centered vertically within that 2/3.

**Comment by elixirgraphics** [comment]
Added as an optional toggle: 

![screen shot 2017-09-18 at 4 59 48 pm](https://user-images.githubusercontent.com/2013801/30564393-cfb66100-9c92-11e7-9066-ce7d8d954bc4.png)
