### ISSUE TITLE
Alert stack style not linked to Foundry base settings

### ISSUE THREAD

**Issue by webinjection** [elixirgraphics/foundry_issue_tracker#58]
Alert stack styles are the default bootstrap colours rather than from what is set in the Foundry base stack.

**Comment by elixirgraphics** [comment]
Seems like it is working here. Can you provide me with an example project file where it is not working as you'd expect? 

![screen shot 2017-06-20 at 8 48 21 am](https://user-images.githubusercontent.com/2013801/27334048-ff319b32-5595-11e7-922b-cc769923e00d.png)

**Comment by webinjection** [comment]
Ah, silly me, I was expecting them to change based on the main "Brand Colors" setting higher up.  Didn't scroll down!

**Comment by elixirgraphics** [comment]
No problem. Fixed!  😄
