### ISSUE TITLE
Shift icons show on refresh, even if hidden.

### ISSUE THREAD

**Issue by vmcosta** [elixirgraphics/foundry_issue_tracker#73]
So I tried the new Shift stack from Potion Pack and I've hided the icons, but they still they still pop out temporarily, Here's a preview of the icons showing on the left side.

Check it live here: https://preview.egomade.com/aim/

[Sep-09-2017 18-20-59.mp4.zip](https://github.com/elixirgraphics/foundry_issue_tracker/files/1289956/Sep-09-2017.18-20-59.mp4.zip)

**Comment by elixirgraphics** [comment]
Won't be able to look at this over the weekend. Maybe not until monday. Sorry.

**Comment by vmcosta** [comment]
No problem at all Adam, just reporting so that we can fix it in time, keep safe.

**Comment by elixirgraphics** [comment]
Send me a ZIP file with your project file so I can have a look at it specifically. I've not ever run into this with my testing, so maybe it is a corner case.

**Comment by elixirgraphics** [comment]
Back to working on this Shift bug today @vmcosta. Think I might have it. Give this link a test: https://elixirgraphics.com/test/shift-icon-test/

I've used some really large photos so that load times will be slower than normal. Let me know if you see the icons. If not, I will publish with your project file and we'll see if it happens still with it. Speaking of which, if you could resend that to me I would appreciate it. I can't seem to find it. Think it got swept up in a mass cleaning of my Desktop.

**Comment by vmcosta** [comment]
@elixirgraphics It seams that is fixed on your example, for the project file "AIM" please check your messages on Slack it is there, if not let me know and send you a new link.

**Comment by elixirgraphics** [comment]
Indeed, you are correct. I will download it and give it a go again.

**Comment by elixirgraphics** [comment]
Uploaded a test, let me know if you see problems: https://elixirgraphics.com/test/aim-test-2/

**Comment by vmcosta** [comment]
Just tried on, can't seam to figure out why it happens, maybe related to google fonts loading. https://dsh.re/58f93

**Comment by elixirgraphics** [comment]
I tested it several times here with no problems. Retested after getting your message and now I get the problem again. 🙄

So I started more troubleshooting, this time on your project file itself. When I look at your Typeface stack, within the Partial it looks odd and isn't displaying properly.

<img width="992" alt="screen shot 2017-09-21 at 8 19 38 pm" src="https://user-images.githubusercontent.com/2013801/30724169-3a3db59a-9f0a-11e7-9fc7-334012814a09.png">

So I deleted it and re-created it, like so:

<img width="991" alt="screen shot 2017-09-21 at 8 20 17 pm" src="https://user-images.githubusercontent.com/2013801/30724184-515dda16-9f0a-11e7-8065-c91d26abaf39.png">

That being said I saw no changes in the problem. Sometimes I see it, sometimes I don't.

So I worked through some more CSS tweaks, and _may_ have it this time (?).

Give it a shot and see if you can't break it: https://elixirgraphics.com/test/aim-test-3/

**Comment by vmcosta** [comment]
Adam I could not break it :) It seams that everything's ok this time.
The reason you did not see the font displaying in the project file is because I use "Collapse in Edit Mode".

**Comment by elixirgraphics** [comment]
> Adam I could not break it :) It seams that everything's ok this time.
 
Music to my ears!

>The reason you did not see the font displaying in the project file is because I use "Collapse in Edit Mode".

I was so caught up in tracking down bugs that I overlooked the obvious. Duh.
