### ISSUE TITLE
on hover underline non active nav item

### ISSUE THREAD

**Issue by sjenkin3** [elixirgraphics/foundry_issue_tracker#78]
When the Use underline indicator for the navbar stack, have an option or as the normal behavior, on hover of the non-active nav item show the the underline for that nav item.

**Comment by elixirgraphics** [comment]
For this you're looking to have the underline appear on the non-active items when they're hovered over? If so, I'll have a look. Not sure it I'd make that a default, but if it works it could be an option to toggle on.

**Comment by elixirgraphics** [comment]
For this you're looking to have the underline appear on the non-active items when they're hovered over? If so, I'll have a look. Not sure it I'd make that a default, but if it works it could be an option to toggle on.

**Comment by sjenkin3** [comment]
Yes.

**Comment by elixirgraphics** [comment]
Added. Will be in beta 1.3.3.3.
