### ISSUE TITLE
Issue when using Reveal inside Margin stack

### ISSUE THREAD

**Issue by webinjection** [elixirgraphics/foundry_issue_tracker#86]
![image](https://user-images.githubusercontent.com/25494037/32684260-0b7a8dc0-c6d6-11e7-9447-1eb84c20db31.png)
If a Reveal stack is used INSIDE a Margin stack, there's an issue with the way the margins are then displayed showing white space.
- This doesn't happen if Reveal is used OUTSIDE the Margin stack
- This doesn't happen if you use Animagic instead of Reveal

**Comment by elixirgraphics** [comment]
@webinjection: Can you send me a project file for testing? I think I know the answer to this one, and don't think it is a bug, but want to look at it in detail when I'm in the office next.

**Comment by webinjection** [comment]
Actually, not a bug, just me!  I was SURE I was using padding and not margins but double checked my file before sending it to you.

**Comment by elixirgraphics** [comment]
No problem!
